- name: create directory
  file:
    path: /home/ubuntu
    state: directory

- name: create command
  copy:
    content: |
       #!/bin/bash
       #kubectl
       curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
       sudo chmod +x ./kubectl
       sudo mv ./kubectl /usr/local/bin/kubectl
       #rke
       curl -s https://api.github.com/repos/rancher/rke/releases/latest | grep download_url | grep amd64 | cut -d '"' -f 4 | wget -qi -
       sudo chmod +x rke_linux-amd64
       sudo mv rke_linux-amd64 /usr/local/bin/rke
       # helm
       curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
       sudo chmod 777 get_helm.sh
    dest: /home/ubuntu/install_kubectl_rke_helm.sh
    mode: a+x
  tags: cmd
  when: inventory_hostname == "rke-ssh"

- name: run script
  shell: sh /home/ubuntu/install_kubectl_rke_helm.sh
  when: inventory_hostname == "rke-ssh"

- name: run script helm
  shell: /home/ubuntu/get_helm.sh
  when: inventory_hostname == "rke-ssh"

- name: create file rke cluster
  file:
    path: /home/ubuntu/cluster.yml
    state: touch
    mode: '0644'
  when: inventory_hostname == "rke-ssh"

- name: config file cluste
  template: 
     src: cluster.yml.j2
     dest: /home/ubuntu/cluster.yml
  when: inventory_hostname == "rke-ssh"

- name: Run RKE UP
  shell: rke up
  args:
    chdir: /home/ubuntu/
  when: inventory_hostname == "rke-ssh"

- name: run script helm
  command: export KUBECONFIG=/home/ubuntu/kube_config_cluster.yml
  tags: cmd
  when: inventory_hostname == "rke-ssh"
