- name: run curl
  shell: "curl https://releases.rancher.com/install-docker/20.10.sh | sudo bash -"
  when: inventory_hostname in ['rke-master', 'rke-worker']

- name: check version docker
  command: docker --version
  register: docker_version_output
  when: inventory_hostname in ['rke-master', 'rke-worker']

- name: print docker version
  debug:
    var: docker_version_output.stdout_lines
  when: inventory_hostname in ['rke-master', 'rke-worker']

- name: config sshd_config file
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowTcpForwarding'
    line: 'AllowTcpForwarding yes'
    backup: yes
  when: inventory_hostname in ['rke-master', 'rke-worker']

- name: restart sshd service
  become: true
  service:
    name: sshd
    state: restarted
  when: inventory_hostname in ['rke-master', 'rke-worker']

- name: Grand permission docker
  become: true
  shell: "sudo chmod 777 /var/run/docker.sock"
  when: inventory_hostname in ['rke-master', 'rke-worker']
